spring:
  profiles:
    active: dev

---
spring:
  profiles: 
    active: dev
  application:
    name: springcloud-config-dev


---
spring:
  profiles:
    active: test 
  application:
    name: springcloud-config-test